import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RuntimeProviderEdge } from "@/lib/chat/runtime-provider-edge";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RuntimeProviderEdge api='/api/dify?userId=user123'>
      <html lang="en" className="h-full">
        <body className={`${inter.className} h-full`}>{children}</body>
      </html>
    </RuntimeProviderEdge>
  );
}
